from datetime import datetime

import scrapy
from scrapy.http import HtmlResponse

from data_tools.message import ForumMessage
from scraper.spiders.dummy.categories import DummyCategory


class DummySpider(scrapy.Spider):

    name = "dummy"

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def start_requests(self):
        # List of URLs to be parsed. Like URLs to forum threads.
        urls = ["http://www.google.com"]
        for url in urls:
            yield scrapy.Request(url=url, callback=self.parse)

    def parse(self, response: HtmlResponse, **kwargs):
        # When you implement a proper spider, the response object should be parsed for an actual message.
        yield ForumMessage(
            msg_id=0,
            thread_id=0,
            date=datetime.now(),
            is_first_in_thread=True,
            category=DummyCategory.DefaultCategory,
            author="someone",
            title="Dummy Message Title",
            msg="*** [This is a dummy message generated by DummySpider] ***",
        )
